language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "9"
  - "10"
  - "12"
  - "14"

cache: yarn

install:
  - npm install --global yarn@1.10.1
  - yarn --version
  - yarn install

script:
  - yarn test

jobs:
  include:
    - stage: npm release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: "echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc && npm publish"
        on:
          branch: master
